// <auto-generated />
namespace JopOffere.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addrole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addrole));
        
        string IMigrationMetadata.Id
        {
            get { return "202103240158548_Addrole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
